$(document).ready(function()
{
	$('#body').ready(function()
	{
		$('#about').ready(function()
		{
			$('#about').click(function()
			{
				$('#body').empty();
				$('#body').load('pages/about.html');
			});
		});
		
		$('#portfolio').ready(function()
		{
			$('#portfolio').click(function()
			{
				$('#body').empty();
				$('#body').load('pages/portfolio.html');
			});
		});
		
		$('#resume').ready(function()
		{
			$('#resume').click(function()
			{
				$('#body').empty();
				$('#body').load('pages/resume.html');
			});
		});

		$('#clients').ready(function()
		{
			$('#clients').click(function()
			{
				$('#body').empty();
				$('#body').load('pages/clients.html');
			});
		});
	});
});
