$(document).ready(function()
{
	$('#header').ready(function()
	{
		$('#about').click(function()
		{
			$('#body').ready(function()
			{
				$('#body').empty();
				$('#body').load('pages/about.html');
			});
		});
		
		$('#portfolio').click(function()
		{
			$('#portfolio').ready(function()
			{
				$('#body').empty();
				$('#body').load('pages/portfolio.html');
			});
		});
		
		$('#resume').click(function()
		{
			$('#resume').ready(function()
			{
				$('#body').empty();
				$('#body').load('pages/resume.html');
			});
		});

		$('#clients').click(function()
		{
			$('#clients').ready(function()
			{
				$('#body').empty();
				$('#body').load('pages/clients.html');
			});
		});
	});
});
